# Generated by Django 6.0.1 on 2026-02-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_team_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email_sent',
        ),
    ]
