# Generated by Django 6.0.1 on 2026-02-08 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_team_payment_id_team_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('CSIT', 'CSIT'), ('AIML', 'AIML'), ('OTHERS', 'OTHERS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd')], max_length=1),
        ),
    ]
