# Generated by Django 6.0.1 on 2026-02-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_team_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
